name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod setup

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS IPA
        run: |
          flutter build ios --release --no-codesign
          cd "${FLUTTER_BUILD_DIR}" || exit 1 # Navigate to Flutter build directory
          cd ios || exit 1 # Navigate to ios directory
          pod install
          cd ..
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
          mv app.ipa ../../../app.ipa

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
